algoritmo "semnome"
// Função :
// Autor :
// Data : 13/11/2019
// Seção de Declarações
var

A, B, C: vetor[1..20] de inteiro

i: inteiro

posicao: inteiro

inicio
// Seção de Comandos

para i de 1 ate 20 faca

   leia (A[i])

fimpara

para i de 1 ate 20 faca

   Leia (B[i])

fimpara

para i de 1 ate 20 faca

   C[i] <- A[i] - B[i]

   escreva (B[i])

fimpara

fimalgoritmo
