algoritmo "semnome"
// Função :
// Autor :
// Data : 12/11/2019
// Seção de Declarações
var

i, numero, soma: inteiro

inicio
// Seção de Comandos

escreva("Deseja somar até qual número: ")

leia(numero)

soma:= 1

Escreval("Pares: ")

para i de 1 ate numero faca

   se (i mod 2 = 0) entao

      escreva("(",i,")")

      soma:= soma + i

   fimse

fimpara

escreval(" ")

escreval("O resultado da soma dos pares é: ", soma)

Fimalgoritmo


