algoritmo "semnome"
// Função :
// Autor :
// Data : 10/10/2019
// Seção de Declarações 

var

bmaior, bmenor, altura, area: real

inicio
// Seção de Comandos

escreva("Ditite o valor da base maior: ")
leia(bmaior)

escreva("Ditite o valor da base menor: ")
leia(bmenor)

escreva("Ditite o valor da altura: ")
leia(altura)

area:= ((bmaior+bmenor) *altura) /2

escreva("O valor da area é de:", area)

fimalgoritmo
