algoritmo "semnome"
// Função :
// Autor :
// Data : 15/10/2019
// Seção de Declarações 

var

nome: logico

n1, n2: inteiro

inicio
// Seção de Comandos

escreva("Digite o seu nome: ")
leia(nome)

escreva("Digite um numero: ")
leia(n1)

escreva("Digite um numero: ")
leia(n1)

resultado:= n1 <= n2

escreval("pergunta:",n1, " eh menor que", n2, "?")

escreva("resposta:")

escreva(resultado)



fimalgoritmo
