algoritmo "semnome"
// Função :
// Autor :
// Data : 10/10/2019
// Seção de Declarações 
var

numero1, numero2 : real

inicio
// Seção de Comandos 

escreva ("Digite um numero: ")
leia (numero1)
escreva ("Digite um numero: ")
leia (numero2)


escreva("A soma é: ", numero1+numero2)

escreva("A subtração é: ", numero1-numero2)

escreva("A multiplicação é: ", numero1*numero2)

escreva("A divisão é: ", numero1/numero2)


fimalgoritmo

