algoritmo "semnome"
// Função :
// Autor :
// Data : 15/10/2019
// Seção de Declarações 

var

consumo, distancia, total: real

inicio
// Seção de Comandos

escreva("Digite a distancia percorrida: ")
leia(distancia)

escreva("Digite o consumo: ")
leia(consumo)

total:= (distancia * consumo)

escreval("O total percorrido do automovel foi:", total, "km")

escreval("E o total de combustivel gasto do automovel foi:", total, "reais")






fimalgoritmo
